export { Hero } from "./Hero";
export { Metricas } from "./Metricas";
export { ElMarcador } from "./ElMarcador";
export { ComoFuncionaResumen } from "./ComoFuncionaResumen";
export { CiudadesCards } from "./CiudadesCards";
export { FeedInstagram } from "./FeedInstagram";
export { MuroLlavesPreview } from "./MuroLlavesPreview";
export { Testimonios } from "./Testimonios";
export { CTAFinal } from "./CTAFinal";
